export const Data = [
    {
        id: 0,
        name: 'item01',
        reviews: '4.55/5',
        price: '199.99',
        description: 'A sturdy and lor spacious desk for your home office or workspace.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'IKEA',
        image: 'desk.jpg',
        category: 'office',
        colors: ['White', 'Black', 'Brown'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 1,
        name: 'Desk',
        reviews: '4.5/5',
        price: '199.99',
        description: 'A sturdy and spacious desk for your home office or workspace.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'IKEA',
        image: 'desk.jpg',
        category: 'office',
        colors: ['White', 'Black', 'Brown'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 2,
        name: 'Sofa',
        reviews: '4.2/5',
        price: '499.99',
        description: 'A comfortable sofa with plush cushions for your living room.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Ashley Furniture',
        image: 'sofa.jpg',
        category: 'living',
        colors: ['Gray', 'Beige', 'Navy'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 3,
        name: 'Blender',
        reviews: '4.8/5',
        price: '79.99',
        description: 'A powerful blender for making smoothies and other delicious recipes.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Ninja',
        image: 'blender.jpg',
        category: 'kitchen',
        colors: ['Red', 'Black', 'Silver'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 4,
        name: 'Queen Bed',
        reviews: '4.6/5',
        price: '699.99',
        description: 'A stylish and comfortable queen-size bed for your bedroom.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 0,
        brand: 'Sealy',
        image: 'bed.jpg',
        category: 'bedroom',
        colors: ['White', 'Brown', 'Gray'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 5,
        name: 'Dining Table',
        reviews: '4.4/5',
        price: '299.99',
        description: 'A durable dining table that can accommodate your family and guests.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Wayfair',
        image: 'dining_table.jpg',
        category: 'dining',
        colors: ['Oak', 'Espresso', 'White'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 6,
        name: 'Toy Chest',
        reviews: '4.0/5',
        price: '49.99',
        description: 'A fun and spacious toy chest to keep your kids\' toys organized.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Step2',
        image: 'toy_chest.jpg',
        category: 'kids',
        colors: ['Blue', 'Pink', 'Purple'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 7,
        name: 'Office Chair',
        reviews: '4.3/5',
        price: '129.99',
        description: 'An ergonomic office chair for comfortable and productive work hours.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Herman Miller',
        image: 'office_chair.jpg',
        category: 'office',
        colors: ['Black', 'Gray', 'Blue'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 8,
        name: 'TV Stand',
        reviews: '4.7/5',
        price: '199.99',
        description: 'A sleek and modern TV stand to showcase your entertainment setup.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Walker Edison',
        image: 'tv_stand.jpg',
        category: 'living',
        colors: ['White', 'Black', 'Brown'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 9,
        name: 'Toaster',
        reviews: '4.1/5',
        price: '39.99',
        description: 'A compact and efficient toaster for your kitchen.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 0,
        brand: 'Cuisinart',
        image: 'toaster.jpg',
        category: 'kitchen',
        colors: ['Silver', 'Red', 'Black'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 10,
        name: 'Nightstand',
        reviews: '4.6/5',
        price: '149.99',
        description: 'A stylish nightstand to complement your bedroom decor.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Pottery Barn',
        image: 'nightstand.jpg',
        category: 'bedroom',
        colors: ['White', 'Espresso', 'Gray'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 11,
        name: 'Dining Chairs (Set of 4)',
        reviews: '4.0/5',
        price: '199.99',
        description: 'A set of four comfortable and elegant dining chairs.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'West Elm',
        image: 'dining_chairs.jpg',
        category: 'dining',
        colors: ['Gray', 'Beige', 'Navy'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 12,
        name: 'Play Kitchen',
        reviews: '4.9/5',
        price: '129.99',
        description: 'A delightful play kitchen set for your kids to explore their culinary skills.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'KidKraft',
        image: 'play_kitchen.jpg',
        category: 'kids',
        colors: ['Pink', 'Blue', 'Red'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 13,
        name: 'Desk Lamp',
        reviews: '4.2/5',
        price: '29.99',
        description: 'A functional and adjustable desk lamp for your workspace.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'IKEA',
        image: 'desk_lamp.jpg',
        category: 'office',
        colors: ['White', 'Black', 'Silver'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 14,
        name: 'Recliner',
        reviews: '4.7/5',
        price: '599.99',
        description: 'A luxurious recliner to relax and unwind in your living room.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'La-Z-Boy',
        image: 'recliner.jpg',
        category: 'living',
        colors: ['Brown', 'Black', 'Gray'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 15,
        name: 'Coffee Maker',
        reviews: '3.5/5',
        price: '79.99',
        description: 'A programmable coffee maker to brew your favorite morning coffee.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 0,
        brand: 'Keurig',
        image: 'coffee_maker.jpg',
        category: 'kitchen',
        colors: ['Black', 'Silver', 'Red'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 16,
        name: 'Storage Ottoman',
        reviews: '4.8/5',
        price: '89.99',
        description: 'A versatile storage ottoman to keep your living room organized.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'HomePop',
        image: 'ottoman.jpg',
        category: 'living',
        colors: ['Gray', 'Beige', 'Navy'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 17,
        name: 'Rice Cooker',
        reviews: '4.3/5',
        price: '49.99',
        description: 'An efficient rice cooker for perfectly cooked rice every time.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Zojirushi',
        image: 'rice_cooker.jpg',
        category: 'kitchen',
        colors: ['White', 'Black', 'Stainless Steel'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 18,
        name: 'Queen Mattress',
        reviews: '4.6/5',
        price: '899.99',
        description: 'A comfortable and supportive queen-size mattress for a good night\'s sleep.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'Tempur-Pedic',
        image: 'mattress.jpg',
        category: 'bedroom',
        colors: ['White', 'Gray', 'Beige'],
        freeShip: 1,
        quantity: 0,
    },
    {
        id: 19,
        name: 'Bar Cart',
        reviews: '4.1/5',
        price: '149.99',
        description: 'A stylish bar cart to display and serve your favorite beverages.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 0,
        brand: 'CB2',
        image: 'bar_cart.jpg',
        category: 'dining',
        colors: ['Gold', 'Black', 'White'],
        freeShip: 0,
        quantity: 0,
    },
    {
        id: 20,
        name: 'Children\'s Bookshelf',
        reviews: '4.5/5',
        price: '79.99',
        description: 'A colorful bookshelf to encourage your kids\' love for reading.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus veniam perspiciatis, recusandae perferendis qui ipsa, porro cum architecto sed ex, cumque tempore! Voluptates iste repellendus repudiandae a recusandae labore suscipit hic facere beatae ratione. Rem quos repudiandae nihil minus facere.',
        available: 1,
        brand: 'KidKraft',
        image: 'bookshelf.jpg',
        category: 'kids',
        colors: ['Red', 'Blue', 'Yellow'],
        freeShip: 1,
        quantity: 0,
    }
]
